# Logistic Regression

In [1]:
# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Load and preprocess the dataset
df = pd.read_csv('./bankruptcy_data.csv')
df.head(10)

Bankrupt   ROA(C) before interest and depreciation before interest  \
0         1                                           0.370594          
1         1                                           0.464291          
2         1                                           0.426071          
3         1                                           0.399844          
4         1                                           0.465022          
5         1                                           0.388680          
6         0                                           0.390923          
7         0                                           0.508361          
8         0                                           0.488519          
9         0                                           0.495686          

    ROA(A) before interest and % after tax  \
0                                 0.424389   
1                                 0.538214   
2                                 0.499019   
3                                 0.451265   
4                                 0.538432   
5                                 0.415177   
6                                 0.445704   
7                                 0.570922   
8                                 0.545137   
9                                 0.550916   

    ROA(B) before interest and depreciation after tax  \
0                                           0.405750    
1                                           0.516730    
2                                           0.472295    
3                                           0.457733    
4                                           0.522298    
5                                           0.419134    
6                                           0.436158    
7                                           0.559077    
8                                           0.543284    
9                                           0.542963    

    Operating Gross Margin   Realized Sales Gross Margin  \
0                 0.601457                      0.601457   
1                 0.610235                      0.610235   
2                 0.601450                      0.601364   
3                 0.583541                      0.583541   
4                 0.598783                      0.598783   
5                 0.590171                      0.590251   
6                 0.619950                      0.619950   
7                 0.601738                      0.601717   
8                 0.603612                      0.603612   
9                 0.599209                      0.599209   

    Operating Profit Rate   Pre-tax net Interest Rate  \
0                0.998969                    0.796887   
1                0.998946                    0.797380   
2                0.998857                    0.796403   
3                0.998700                    0.796967   
4                0.998973                    0.797366   
5                0.998758                    0.796903   
6                0.998993                    0.797012   
7                0.999009                    0.797449   
8                0.998961                    0.797414   
9                0.999001                    0.797404   

    After-tax net Interest Rate   Non-industry income and expenditure/revenue  \
0                      0.808809                                      0.302646   
1                      0.809301                                      0.303556   
2                      0.808388                                      0.302035   
3                      0.808966                                      0.303350   
4                      0.809304                                      0.303475   
5                      0.808771                                      0.303116   
6                      0.808960                                      0.302814   
7                      0.809362                                      0.303545   
8                      0.809338               

## Exploratory Data Analysis

In [3]:
df.shape

(6819, 96)

In [4]:
df.columns

Index(['Bankrupt', ' ROA(C) before interest and depreciation before interest',
       ' ROA(A) before interest and % after tax',
       ' ROA(B) before interest and depreciation after tax',
       ' Operating Gross Margin', ' Realized Sales Gross Margin',
       ' Operating Profit Rate', ' Pre-tax net Interest Rate',
       ' After-tax net Interest Rate',
       ' Non-industry income and expenditure/revenue',
       ' Continuous interest rate (after tax)', ' Operating Expense Rate',
       ' Research and development expense rate', ' Cash flow rate',
       ' Interest-bearing debt interest rate', ' Tax rate (A)',
       ' Net Value Per Share (B)', ' Net Value Per Share (A)',
       ' Net Value Per Share (C)', ' Persistent EPS in the Last Four Seasons',
       ' Cash Flow Per Share', ' Revenue Per Share (Yuan ¥)',
       ' Operating Profit Per Share (Yuan ¥)',
       ' Per Share Net profit before tax (Yuan ¥)',
       ' Realized Sales Gross Profit Growth Rate',
       ' Operating Profit 

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6819 entries, 0 to 6818
Data columns (total 96 columns):
 #   Column                                                    Non-Null Count  Dtype  
---  ------                                                    --------------  -----  
 0   Bankrupt                                                  6819 non-null   int64  
 1    ROA(C) before interest and depreciation before interest  6819 non-null   float64
 2    ROA(A) before interest and % after tax                   6819 non-null   float64
 3    ROA(B) before interest and depreciation after tax        6819 non-null   float64
 4    Operating Gross Margin                                   6819 non-null   float64
 5    Realized Sales Gross Margin                              6819 non-null   float64
 6    Operating Profit Rate                                    6819 non-null   float64
 7    Pre-tax net Interest Rate                                6819 non-null   float64
 8    After-tax net Int

In [6]:
df.describe()

Bankrupt   ROA(C) before interest and depreciation before interest  \
count  6819.000000                                        6819.000000          
mean      0.032263                                           0.505180          
std       0.176710                                           0.060686          
min       0.000000                                           0.000000          
25%       0.000000                                           0.476527          
50%       0.000000                                           0.502706          
75%       0.000000                                           0.535563          
max       1.000000                                           1.000000          

        ROA(A) before interest and % after tax  \
count                              6819.000000   
mean                                  0.558625   
std                                   0.065620   
min                                   0.000000   
25%                                   0.535543   
50%                                   0.559802   
75%                                   0.589157   
max                                   1.000000   

        ROA(B) before interest and depreciation after tax  \
count                                        6819.000000    
mean                                            0.553589    
std                                             0.061595    
min                                             0.000000    
25%                                             0.527277    
50%                                             0.552278    
75%                                             0.584105    
max                                             1.000000    

        Operating Gross Margin   Realized Sales Gross Margin  \
count              6819.000000                   6819.000000   
mean                  0.607948                      0.607929   
std                   0.016934                      0.016916   
min                   0.000000                      0.000000   
25%                   0.600445                      0.600434   
50%                   0.605997                      0.605976   
75%                   0.613914                      0.613842   
max                   1.000000                      1.000000   

        Operating Profit Rate   Pre-tax net Interest Rate  \
count             6819.000000                 6819.000000   
mean                 0.998755                    0.797190   
std                  0.013010                    0.012869   
min                  0.000000                    0.000000   
25%                  0.998969                    0.797386   
50%                  0.999022                    0.797464   
75%                  0.999095                    0.797579   
max                  1.000000                    1.000000   

        After-tax net Interest Rate  \
count                   6819.000000   
mean                       0.809084   
std                        0.013601   
min                        0.000000   
25%                        0.809312   
50%                        0.809375   
75%                        0.809469   
max                        1.000000   

        Non-industry income and expenditure/revenue  ...  \
count                                   6819.000000  ...   
mean                                       0.303623  ...   
std                                        0.011163  ...   
min                                        0.000000  ...   
25%                                        0.303466  ...   
50%                                        0.303525  ...   
75%                                        0.303585  ...   
max                                        1.000000  ...   

        Net Income to Total Assets   Total assets to GNP price  \
count                  6819.000000                6.819000e+03   
mean                      0.807760                1.862942e+07   
std                       0.040332                3.764501e+08   
min 

In [7]:
df.isnull().sum()

Bankrupt                                                    0
 ROA(C) before interest and depreciation before interest    0
 ROA(A) before interest and % after tax                     0
 ROA(B) before interest and depreciation after tax          0
 Operating Gross Margin                                     0
                                                           ..
 Liability to Equity                                        0
 Degree of Financial Leverage (DFL)                         0
 Interest Coverage Ratio (Interest expense to EBIT)         0
 Net Income Flag                                            0
 Equity to Liability                                        0
Length: 96, dtype: int64

In [8]:
cols = [col for col in df.columns if col != 'Bankrupt']

for col in cols:
    std_dev = df[col].std()
    mean = df[col].mean()
    outliers = df[(df[col] - mean).abs() > 3 * std_dev]
    print(f'Column: {col}, Outliers: {len(outliers)}')

Column:  ROA(C) before interest and depreciation before interest, Outliers: 88
Column:  ROA(A) before interest and % after tax, Outliers: 110
Column:  ROA(B) before interest and depreciation after tax, Outliers: 101
Column:  Operating Gross Margin, Outliers: 63
Column:  Realized Sales Gross Margin, Outliers: 63
Column:  Operating Profit Rate, Outliers: 2
Column:  Pre-tax net Interest Rate, Outliers: 7
Column:  After-tax net Interest Rate, Outliers: 7
Column:  Non-industry income and expenditure/revenue, Outliers: 6
Column:  Continuous interest rate (after tax), Outliers: 7
Column:  Operating Expense Rate, Outliers: 0
Column:  Research and development expense rate, Outliers: 35
Column:  Cash flow rate, Outliers: 89
Column:  Interest-bearing debt interest rate, Outliers: 146
Column:  Tax rate (A), Outliers: 114
Column:  Net Value Per Share (B), Outliers: 115
Column:  Net Value Per Share (A), Outliers: 115
Column:  Net Value Per Share (C), Outliers: 115
Column:  Persistent EPS in the Last

In [9]:
# TODO: Handle Outliers

## Pairplots

In [10]:
# Plotting one feature against every other feature
# plt.figure(figsize=(20, 6))
# sns.pairplot(df, hue='Bankrupt', vars=cols[:5])
# plt.show()

## Training the model

In [11]:
# Prepare data for modeling
X = df.drop('Bankrupt', axis=1).values
y = df['Bankrupt'].values

In [12]:
X[0]

array([3.70594257e-01, 4.24389446e-01, 4.05749772e-01, 6.01457213e-01,
       6.01457213e-01, 9.98969203e-01, 7.96887146e-01, 8.08809361e-01,
       3.02646434e-01, 7.80984850e-01, 1.25697000e-04, 0.00000000e+00,
       4.58143144e-01, 7.25073000e-04, 0.00000000e+00, 1.47949939e-01,
       1.47949939e-01, 1.47949939e-01, 1.69140588e-01, 3.11664427e-01,
       1.75597800e-02, 9.59205280e-02, 1.38736160e-01, 2.21022780e-02,
       8.48194995e-01, 6.88979463e-01, 6.88979463e-01, 2.17535386e-01,
       4.98000000e+09, 3.26977000e-04, 2.63099984e-01, 3.63725271e-01,
       2.25896300e-03, 1.20775500e-03, 6.29951302e-01, 2.12659240e-02,
       2.07576261e-01, 7.92423739e-01, 5.02445500e-03, 3.90284354e-01,
       6.47850200e-03, 9.58848340e-02, 1.37757334e-01, 3.98035698e-01,
       8.69565220e-02, 1.81388400e-03, 3.48736400e-03, 1.82093000e-04,
       1.16501000e-04, 3.29032260e-02, 3.41641820e-02, 3.92912869e-01,
       3.71353020e-02, 6.72775292e-01, 1.66672959e-01, 1.90642959e-01,
      

In [13]:
def split_data(X, y, test_size=0.2, random_state=42):
    np.random.seed(random_state)
    n = X.shape[0]
    indices = np.arange(n)
    np.random.shuffle(indices)
    
    test_size = int(test_size * n)
    test_indices = indices[:test_size]
    train_indices = indices[test_size:]
    
    X_train, X_test = X[train_indices], X[test_indices]
    y_train, y_test = y[train_indices], y[test_indices]
    
    return X_train, X_test, y_train, y_test

In [14]:
X_train, X_test, y_train, y_test = split_data(X, y)

In [15]:
# Compute training statistics
train_mean = X_train.mean(axis=0)
train_std = X_train.std(axis=0)
std_safe = np.where(train_std == 0, 1, train_std)

# Standardize using training stats
X_train = (X_train - train_mean) / std_safe
X_test = (X_test - train_mean) / std_safe

# Add bias column (intercept term)
X_train = np.hstack((np.ones((X_train.shape[0], 1)), X_train))
X_test = np.hstack((np.ones((X_test.shape[0], 1)), X_test))

In [16]:
X_train[0]

array([ 1.        ,  0.75530414,  0.72669803,  0.96322629,  1.45154619,
        1.454285  ,  0.02309349,  0.03758693,  0.03712321,  0.01937728,
        0.0396159 , -0.62124138, -0.75375164,  0.61661328,  2.51915345,
       -0.83962579,  0.2903308 ,  0.29063702,  0.28959609,  0.51381386,
        0.43549825, -0.02559328, -0.20353498,  0.26303161, -0.02668823,
        0.00324782,  0.00993624,  0.00922549, -0.00822424,  0.5679319 ,
       -0.0135395 , -0.07774427,  0.38258119, -0.0135395 , -0.02846031,
       -0.03189536, -0.02826617, -0.77207525,  0.77207525, -0.08056222,
       -0.26106982, -0.04778276, -0.20165259,  0.30880307, -0.57759583,
       -0.46957945, -0.04355796, -0.03286235, -0.65737911, -0.40436865,
       -0.43291727, -0.01903263, -0.14822428, -0.0389377 , -0.85205518,
       -0.98318484, -1.44910599, -0.59600446, -0.01913549, -0.0641647 ,
       -0.79314172,  0.5644996 , -0.02350016, -0.09549672, -0.52698833,
       -0.2467912 , -0.2556299 , -0.0908879 ,  0.45889789, -0.01

In [17]:
X_test[0]

array([ 1.00000000e+00, -1.16605945e+00, -1.18506214e+00, -8.94963169e-01,
       -6.57710476e-01, -6.57374672e-01,  5.87569244e-03, -9.09578628e-03,
        7.12664872e-04, -3.26386116e-02, -3.11507138e-03, -6.21241378e-01,
        4.17091107e-01,  3.23572943e-01, -1.51505691e-01, -8.39625790e-01,
       -4.94179554e-01, -4.91763527e-01, -4.92568398e-01, -7.79896753e-01,
       -1.90971187e-01, -2.55932831e-02, -7.52620770e-01, -8.04367450e-01,
       -3.44317887e-02, -4.59587083e-01, -2.19552591e-01, -2.19143844e-01,
       -2.37052259e-02,  2.77839804e-02, -1.35394999e-02, -8.31288798e-02,
       -3.42475584e-02, -1.35394998e-02, -2.84603139e-02, -3.21713371e-02,
       -2.82661681e-02, -1.28138463e+00,  1.28138463e+00, -1.46533055e-01,
       -3.03712383e-01,  7.40872107e-02, -7.52527857e-01, -8.52355047e-01,
       -5.14222663e-01, -7.51006791e-01, -4.35579583e-02, -3.28623455e-02,
       -6.57379111e-01,  1.99673951e+00, -5.65679396e-01, -1.90326265e-02,
       -3.44785396e-01, -

In [18]:
# Verify shapes of train and test sets
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((5456, 96), (1363, 96), (5456,), (1363,))

In [19]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [20]:
w = np.zeros(X_train.shape[1])
alpha = 0.1
epochs = 1000
batch_size = 32

In [21]:
for epoch in range(1, epochs + 1):
    # Shuffle each epoch
    indices = np.arange(X_train.shape[0])
    np.random.shuffle(indices)
    X_train = X_train[indices]
    y_train = y_train[indices]
    m_train = X_train.shape[0]

    for start in range(0, m_train, batch_size):
        end = start + batch_size
        X_batch = X_train[start:end]
        y_batch = y_train[start:end]

        m_batch = X_batch.shape[0]
        z = X_batch @ w
        y_pred = sigmoid(z)

        dw = (1 / m_batch) * X_batch.T @ (y_pred - y_batch)
        w -= alpha * dw

    if epoch % 100 == 0:
        z_train = X_train @ w
        y_train_pred = sigmoid(z_train)
        train_loss = - (1 / m_train) * np.sum(
            y_train * np.log(y_train_pred + 1e-15) +
            (1 - y_train) * np.log(1 - y_train_pred + 1e-15)
        )
        print(f'Epoch {epoch}, Loss: {train_loss:.4f}')

Epoch 100, Loss: 0.0800
Epoch 200, Loss: 0.0793
Epoch 300, Loss: 0.0806
Epoch 400, Loss: 0.0782
Epoch 500, Loss: 0.0783
Epoch 600, Loss: 0.0786
Epoch 700, Loss: 0.0780
Epoch 800, Loss: 0.0780
Epoch 900, Loss: 0.0776
Epoch 1000, Loss: 0.0779


In [25]:
z_test = X_test @ w
y_pred_prob = sigmoid(z_test)

y_pred_final = (y_pred_prob >= 0.5).astype(int)

C:\Users\azamm\AppData\Local\Temp\ipykernel_24848\3196251242.py:2: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


In [26]:
comparison = np.vstack((y_test, y_pred)).T
print(comparison[:10])

[[0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [27]:
accuracy = np.mean(y_pred_final == y_test)
print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.9648


In [28]:
TP = np.sum((y_pred == 1) & (y_test == 1))
TN = np.sum((y_pred == 0) & (y_test == 0))
FP = np.sum((y_pred == 1) & (y_test == 0))
FN = np.sum((y_pred == 0) & (y_test == 1))

precision = TP / (TP + FP + 1e-8)
recall = TP / (TP + FN + 1e-8)
f1 = 2 * (precision * recall) / (precision + recall + 1e-8)

print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-score:  {f1:.4f}")

Precision: 0.5714
Recall:    0.2353
F1-score:  0.3333
